version: '3.8'

services:

  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - opentask-net

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: opentask
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - opentask-net

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - opentask-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - opentask-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  # web UI
    networks:
      - opentask-net

networks:
  opentask-net:
    driver: bridge


volumes:
  pg_data:
  mongo_data:
